---
version: "3.8"

services:
  jekyll:
    image: jekyll/jekyll
    container_name: jekyll
    environment:
      - JEKYLL_UID=${JEKYLL_UID}
      - JEKYLL_GID=${JEKYLL_GID}
    ports:
      - 4000:4000
    volumes:
      - ${JEKYLL_SITE_PATH}:/srv/jekyll:Z
      - ${JEKYLL_SITE_PATH}/vendor/bundle:/usr/local/bundle:Z
      - ${JEKYLL_SITE_PATH}/gem:/usr/gem
